version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: "192.168.10.59"
      DB_NAME: messages
      DB_USER: user
      DB_PASS: password
    restart: always
