- hosts: web
  become: yes
  vars:
    db_host: "192.168.10.59"
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install docker-compose
      apt:
        name: docker-compose
        state: present

    - name: Copy app
      copy:
        src: ../studentapp/
        dest: /home/ubuntu/app

    - name: Set DB_HOST in docker-compose
      replace:
        path: /home/ubuntu/app/docker-compose.yml
        regexp: 'DB_HOST:.*'
        replace: 'DB_HOST: "{{ db_host }}"'

    - name: Start app
      command: docker-compose up -d --build
      args:
        chdir: /home/ubuntu/app
